site_name: Star Technology Wiki
site_url: https://start-dev-team.github.io/StarT-Wiki/
repo_name: Star Technology
repo_url: https://github.com/StarT-Dev-Team/Star-Technology
use_directory_urls: true
theme:
  name: material
  custom_dir: overrides
  font:
    text: Merriweather Sans
    code: Red Hat Mono
  logo: assets/logo.png
  favicon: assets/flavicon.ico
  features:
    - navigation.tabs
    - navigation.expand
    - navigation.footer
    - navigation.top
    - navigation.indexes
    - navigation.path
    - toc.follow
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.copy 
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch

  palette:
    # Light Mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: deep purple
      accent: light blue

    #Â Dark Mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: deep purple
      accent: amber

markdown_extensions:
  - toc:
  - attr_list
  - def_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
          config:
            theme: 'base'
            themeVariables:
              primaryColor: '#fff'
              primaryTextColor: '#fff'
              primaryBorderColor: '#7e56c2'
              lineColor: '#F8B195'
              fontSize: '16px'
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde

plugins:
  - search
  - mermaid2
  - panzoom:
      full_screen: True


extra_css:
    - assets/styles/styles.css
    - assets/styles/extra.css

extra_javascript:
    - https://unpkg.com/mermaid/dist/mermaid.min.js


nav:
- Welcome to Star Technology:
  - Home: index.md
  - Meet the Team:
      - Developer Team: 'Meet-the-Team/Developer-Team.md'
      - Credits: 'Meet-the-Team/Credits.md'
  - Contributing to this Wiki: 'Contributing-to-This-Wiki.md'
  - Patch Notes: Patch-Notes.md
  - Challenges: Challenges.md

- Resource Gen:
    - 'Resources/index.md'
    - Resource Production:
        - Hydrogen: 'Resources/Resource-Production/Hydrogen.md'
        - Nitrogen: 'Resources/Resource-Production/Nitrogen.md'
        - Oxygen: 'Resources/Resource-Production/Oxygen.md'
    - Resource Production Machine Lines:
        - Sieving: Resources/Resource-Production-Machines-Lines/Sieving.md
        - Void Extraction: Resources/Resource-Production-Machines-Lines/Void-Extraction.md
        - Rock Filtration: Resources/Resource-Production-Machines-Lines/Rock-Filtration.md
        - Air Distilation: Resources/Resource-Production-Machines-Lines/Air-Distilation.md
        - Drilling Rigs: 'Resources/Resource-Production-Machines-Lines/Drilling Rigs.md'
        - Wood Distilation: Resources/Resource-Production-Machines-Lines/Wood-Distilation
        - Barrel: Resources/Resource-Production-Machines-Lines/Industrial-Barrel.md

- Power Gen:
    - Create Power: 'Mechanics/Energy-Generation/Carbon-Brushes-and-Magnets.md'

- Chemical/Processing Lines:
    - Chemical-Lines/index.md

    - Plastics: 
        - Chemical-Lines/Plastics/index.md
        - Polyethylene: Chemical-Lines/Plastics/Polyethylene.md
        - Polyvinyl Chloride: Chemical-Lines/Plastics/Polyvinyl-Chloride.md
        - Polytetrafluoroethylene: Chemical-Lines/Plastics/Polytetrafluoroethylene.md
        - Polycaprolactam: Chemical-Lines/Plastics/Polycaprolactam.md
        - Polyvinyl Butyral: Chemical-Lines/Plastics/Polyvinyl-Butyral.md
        - Polybenzimidazole: Chemical-Lines/Plastics/Polybenzimidazole.md
        - Polyether Ether Ketone: Chemical-Lines/Plastics/PEEK.md
        
    
    - Rubbers:
        - Latex Rubber: Chemical-Lines/Rubbers/Rubber.md
        - Silicone Rubber: Chemical-Lines/Rubbers/Silicone-Rubber.md
        - Styrene Butadiene: Chemical-Lines/Rubbers/Styrene-Butadiene.md
    - Acids: 
        - Sulfuric Acid: Chemical-Lines/Acids/Sulfuric-Acid.md 
        - Acetic Acid: Chemical-Lines/Acids/Acetic-Acid.md
        - Formic Acid: Chemical-Lines/Acids/Formic-Acid.md
        - Hydrochloric Acid: Chemical-Lines/Acids/Hydrochloric-Acid.md
        - Hydrofluoric Acid: Chemical-Lines/Acids/Hydrofluoric-Acid.md
        - Nitric Acid: Chemical-Lines/Acids/Nitric-Acid.md 

- Multiblocks:
    - LV Multiblocks: Mechanics/GregTech/Multiblocks/LV/LV-Multis.md

- Logisitics:
    - LaserIO:
        - Introduction: Mechanics/LaserIO/LaserIO.md

    - AE2:
        - Introduction: Mechanics/Applied-Energistics-2/AE2-Introduction.md

- Gregtech Mechanics:
    - Electricity: Mechanics/GregTech/Energy.md

- FAQ/Troubleshooting:
    - Contribute: FAQ.md
